### ISSUE TITLE
Build errors on IOS?

### ISSUE THREAD

**Issue by abhlabs** [mboeddeker/disk_space#9]
My app builds and runs without errors for Android, but the build fails for IOS, targeting IOS 12 / iPhone 13.  The build cites numerous warnings in build, but only one error:

`...flutter/.pub-cache/hosted/pub.dartlang.org/disk_space-0.2.1/ios/Classes/DiskSpacePlugin.m:2:9: 
fatal error: 'disk_space/disk_space-Swift.h' file not found
    #import <disk_space/disk_space-Swift.h>`

Removing all references to disk_space package lets the app build and run without errors on iPhone 13 simulator.

It's very possible I've got something set wrong in my xcode project -- I'm very new to xcode (and feeling a little intimidated by the sheer number of settings). Is this an issue in the disk_space package, or is there something wrong with my project settings?

**Comment by abhlabs** [comment]
I was able to resolve the build errors.  If anyone else encounters this problem, read through this SO post: [Build errors on IOS](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io/63955114#63955114) and look for a comment made in response to the question from Ryan Cocuzzo suggesting running Xcode under Rosetta.

**Comment by zhuwei** [comment]
This method won't solve the problem..
